---
- name: Install & configure Nexus. 
  hosts: nexus_server
  remote_user: ubuntu
  become: true 
  tasks: 
  - name: Update apt repo and cache
    apt:
      update_cache: yes

  - name: Install Java 8
    apt:
      name: openjdk-8-jre-headless
      state: latest

  - name: Install net-tools
    apt:
      name: net-tools

  - name: Check nexus folder stats
    stat: 
      path: /opt/nexus
    register: stat_result

  - name: Download Nexus
    get_url:
      url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz 
      dest: /opt
    register: download_result

  - name: Untar Nexus installer
    unarchive: 
      src: "{{download_result.dest}}"
      dest: /opt
      remote_src: yes
    when: not stat_result.stat.exists 

  - name: Find Nexus folder
    find:
      paths: /opt
      pattern: "nexus-*"
      file_type: directory
    register: find_result

  - name: Rename nexus folder
    shell: mv {{find_result.files[0].path}} /opt/nexus
    when: not stat_result.stat.exists 

  - name: Change "Nexus" directory ownership and group 
    file:
      path: /opt/nexus
      state: directory
      owner: ubuntu
      group: ubuntu
      recurse: yes 
      mode: "744"

  - name: Change "sonatype-work" directory ownership and group
    file:
      path: /opt/sonatype-work
      state: directory
      owner: ubuntu
      group: ubuntu
      recurse: yes  
      mode: "744"

  - name:  Set run_as_user nexus
    lineinfile :
      path: /opt/nexus/bin/nexus.rc
      line: run_as_user="ubuntu"
      regexp: '^#run_as_user=""'
      state: present

  - name: Start nexus
    command: /opt/nexus/bin/nexus start

  - name: Check with ps  
    shell: ps aux | grep nexus
    register: app_status
  - debug: msg={{app_status.stdout_lines}}

  - name: wait one minute
    pause: 
      minutes: 1
      
  - name: Check with netstat
    shell: netstat -plnt
    register: app_status

  - debug: msg={{app_status.stdout_lines}}
